name: Auto Rebase Upstream

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  rebase:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: custom-patch
          fetch-depth: 0
          token: ${{ secrets.PAT_TOKEN }} # 빌드 트리거를 위한 PAT 토큰

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add Upstream and Fetch
        run: |
          git remote add upstream https://github.com/rustdesk/rustdesk.git
          git fetch upstream master

      - name: Perform Rebase
        run: |
          git rebase upstream/master
          
      - name: Force Push
        if: success()
        run: |
          git push --force origin custom-patch