name: Flutter Nightly Build

on:
  push:                  # <== 추가 (푸시될 때 동작)
    branches:            # <== 추가 
      - custom-patch     # <== 추가 (custom-patch 브랜치에 변경사항이 생기면)
  schedule:
    # schedule build every night
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  run-flutter-nightly-build:
    uses: ./.github/workflows/flutter-build.yml
    secrets: inherit
    with:
      upload-artifact: true
      upload-tag: "nightly"
